/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.edu.utfpr.view;

import br.edu.utfpr.DAO.FuncionarioDao;
import br.edu.utfpr.DAO.ProdutoDao;
import br.edu.utfpr.DAO.VendaDao;
import br.edu.utfpr.entidades.Funcionario;
import br.edu.utfpr.entidades.Produto;
import br.edu.utfpr.entidades.Venda;
import br.edu.utfpr.model.ProdutoListModel;
import br.edu.utfpr.model.VendaListModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author kelly
 */
public class FormularioVendas extends javax.swing.JInternalFrame {
    ProdutoDao produtoDao = new ProdutoDao();
    FuncionarioDao funcionarioDao = new FuncionarioDao();
    List<Venda> listaVenda = new ArrayList<Venda>();
    VendaListModel vendaListModel = new VendaListModel(listaVenda);
    ProdutoListModel produtoListModel;
    VendaDao vendaDao = new VendaDao();
    /**
     * Creates new form FormularioVendas
     */
    public FormularioVendas() {
        initComponents();
        List<Produto> lista = produtoDao.listar();
        produtoListModel = new ProdutoListModel(lista);       
        tabelaProdutos2.setModel(produtoListModel);
        
        List<Funcionario> listaFuncionarios = funcionarioDao.listar();
        for(Funcionario funcionario : listaFuncionarios){
            int item;
            item = funcionario.getCodigoFuncionario();
            jComboFuncionario.addItem(String.valueOf(item));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        jtCodigo = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        jCEscolha = new javax.swing.JComboBox<>();
        btLimpar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaVendas = new javax.swing.JTable();
        btBuscar1 = new javax.swing.JButton();
        jCEscolha1 = new javax.swing.JComboBox<>();
        btLimpar1 = new javax.swing.JButton();
        btCarrinho = new javax.swing.JButton();
        btVenda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelaProdutos2 = new javax.swing.JTable();
        jComboFuncionario = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTbusca = new javax.swing.JTextField();

        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Setor", "Quantidade", "Preço de custo", "Preço de venda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaProdutos);

        jtCodigo.setColumns(20);

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        jCEscolha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Nome" }));

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        tabelaVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Funcionario", "Produto", "Quantidade", "Preço de venda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelaVendas);

        btBuscar1.setText("Buscar");
        btBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscar1ActionPerformed(evt);
            }
        });

        jCEscolha1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Nome" }));

        btLimpar1.setText("Limpar");
        btLimpar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimpar1ActionPerformed(evt);
            }
        });

        btCarrinho.setText("Vender");
        btCarrinho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCarrinhoActionPerformed(evt);
            }
        });

        btVenda.setText("Abrir recibo");
        btVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVendaActionPerformed(evt);
            }
        });

        jLabel1.setText("Lista de compras");

        tabelaProdutos2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Setor", "Quantidade", "Preço de custo", "Preço de venda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tabelaProdutos2);

        jLabel2.setText("Funcionário:");

        jTbusca.setColumns(20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(jLabel2)
                            .addGap(39, 39, 39)
                            .addComponent(jComboFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btCarrinho))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jCEscolha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTbusca, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btBuscar1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btLimpar1))
                                    .addComponent(jLabel1)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btVenda)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCEscolha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar1)
                    .addComponent(btLimpar1)
                    .addComponent(jTbusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btCarrinho))
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btVenda)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        List<Produto> lista = new ArrayList<>();
        if(jCEscolha.getSelectedItem() == "Nome"){
            lista = produtoDao.buscarPorNome(jTbusca.getText());
        }
        else{
            lista.add(produtoDao.buscarPorCodigo(Integer.parseInt(jTbusca.getText())));
        }

        produtoListModel = new ProdutoListModel(lista);
        tabelaProdutos2.setModel(produtoListModel);
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        jtCodigo.setText("");
        List<Produto> lista = produtoDao.listar();
        produtoListModel = new ProdutoListModel(lista);
        tabelaProdutos2.setModel(produtoListModel);
    }//GEN-LAST:event_btLimparActionPerformed

    private void btBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscar1ActionPerformed
        List<Produto> lista = new ArrayList<>();
        if(jCEscolha.getSelectedItem() == "Nome"){
            lista= produtoDao.buscarPorNome(jTbusca.getText());
        }
        else{
            lista.add(produtoDao.buscarPorCodigo(Integer.parseInt(jTbusca.getText())));
        }

        produtoListModel = new ProdutoListModel(lista);
        tabelaProdutos2.setModel(produtoListModel);
    }//GEN-LAST:event_btBuscar1ActionPerformed

    private void btLimpar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimpar1ActionPerformed
        jtCodigo.setText("");
        List<Produto> lista = produtoDao.listar();
        produtoListModel = new ProdutoListModel(lista);
        tabelaProdutos2.setModel(produtoListModel);
    }//GEN-LAST:event_btLimpar1ActionPerformed

    private void btCarrinhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCarrinhoActionPerformed
        // Input
        int quantidadeVendida = Integer.parseInt(JOptionPane.showInputDialog("Quantidade: "));
        int codigoFuncionario = Integer.parseInt(jComboFuncionario.getSelectedItem().toString());

        // Parse tabela selecao
        int indiceTabelaProduto = tabelaProdutos2.getSelectedRow();
        int codigoProduto = (Integer) produtoListModel.getValueAt(indiceTabelaProduto, 0);
        int qtdeProduto = (Integer) produtoListModel.getValueAt(indiceTabelaProduto, 3);
        double precoProduto = (Double) produtoListModel.getValueAt(indiceTabelaProduto, 5);

        // Carregar dados da base de dados
        ProdutoDao prodDao = new ProdutoDao();
        Produto produto = prodDao.buscarPorCodigo(codigoProduto);
        FuncionarioDao funcDao = new FuncionarioDao();
        Funcionario funcionario = funcDao.buscarPorCodigo(codigoFuncionario);

        // Instanciar venda
        Venda venda = new Venda();
        venda.setQuantidade(quantidadeVendida);
        venda.setValorVenda(precoProduto * quantidadeVendida);
        venda.setFuncionario(funcionario);
        venda.setProduto(produto);
        
        // Atualiza comissao
        funcionario.setComissao(precoProduto * quantidadeVendida * 0.10 + funcionario.getComissao());
        funcDao.alterar(funcionario);
        
        // Salva novo estoque
        produto.setQuantidade(qtdeProduto - quantidadeVendida);
        prodDao.alterar(produto);

        // concretiza a venda
        vendaDao.inserirVenda(venda);
        
        // evento de GUI (Jtable)
        vendaListModel.insertModel(venda);
        tabelaVendas.setModel(vendaListModel);
    }//GEN-LAST:event_btCarrinhoActionPerformed

    private void btVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVendaActionPerformed
        List<Venda> venda = new ArrayList<>();
        int totalRows = tabelaVendas.getRowCount();

        for (int i = 0; i < totalRows; i++) {
            Venda v = new Venda();
            v.setCodigoFuncionario((int) tabelaVendas.getModel().getValueAt(i, 0));
            v.setCodigoProduto((int) tabelaVendas.getModel().getValueAt(i, 1));
            v.setQuantidade((int) tabelaVendas.getModel().getValueAt(i, 2));
            v.setValorVenda((double) tabelaVendas.getModel().getValueAt(i, 3));
            venda.add(v);
        }
        FormularioRecibo fr = new FormularioRecibo(venda);
        fr.setVisible(true);
    }//GEN-LAST:event_btVendaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btBuscar1;
    private javax.swing.JButton btCarrinho;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btLimpar1;
    private javax.swing.JButton btVenda;
    private javax.swing.JComboBox<String> jCEscolha;
    private javax.swing.JComboBox<String> jCEscolha1;
    private javax.swing.JComboBox<String> jComboFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTbusca;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTable tabelaProdutos;
    private javax.swing.JTable tabelaProdutos2;
    private javax.swing.JTable tabelaVendas;
    // End of variables declaration//GEN-END:variables
}
