/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.edu.utfpr.view;

import br.edu.utfpr.DAO.ProdutoDao;
import br.edu.utfpr.entidades.Produto;
import br.edu.utfpr.model.ProdutoListModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author kelly
 */
public class FormularioBuscarProdutos extends javax.swing.JInternalFrame {
    ProdutoDao produtoDao = new ProdutoDao();
    ProdutoListModel produtoListModel;
 
    public FormularioBuscarProdutos() {
        initComponents();
        List<Produto> lista = produtoDao.listar();
        produtoListModel = new ProdutoListModel(lista);       
        tabelaProdutos.setModel(produtoListModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProdutos = new javax.swing.JTable();
        jtCodigo = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        jCEscolha = new javax.swing.JComboBox<>();
        btAtualizar = new javax.swing.JButton();
        btEditarProduto = new javax.swing.JButton();
        btRemoverProduto = new javax.swing.JButton();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Buscar Produtos");

        tabelaProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Setor", "Quantidade", "Preço de custo", "Preço de venda"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabelaProdutos);

        jtCodigo.setColumns(20);

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        jCEscolha.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Código", "Nome" }));

        btAtualizar.setText("Atualizar tabela");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        btEditarProduto.setText("Editar Produto");
        btEditarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarProdutoActionPerformed(evt);
            }
        });

        btRemoverProduto.setText("Remover Produto");
        btRemoverProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(btEditarProduto)
                        .addGap(30, 30, 30)
                        .addComponent(btRemoverProduto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jCEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btAtualizar)
                            .addComponent(btBuscar))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar)
                    .addComponent(jCEscolha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(btAtualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEditarProduto)
                    .addComponent(btRemoverProduto))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        List<Produto> lista = new ArrayList<>();
        if(jCEscolha.getSelectedItem() == "Nome"){
            lista = produtoDao.buscarPorNome(jtCodigo.getText());
        }
        else{
            lista.add(produtoDao.buscarPorCodigo(Integer.parseInt(jtCodigo.getText())));
        }
        
        produtoListModel = new ProdutoListModel(lista);
        tabelaProdutos.setModel(produtoListModel);
    }//GEN-LAST:event_btBuscarActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        jtCodigo.setText("");
        List<Produto> lista = produtoDao.listar();
        produtoListModel = new ProdutoListModel(lista);       
        tabelaProdutos.setModel(produtoListModel);
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void btRemoverProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverProdutoActionPerformed
        int indiceTabela = tabelaProdutos.getSelectedRow();
        int codProduto = (Integer) produtoListModel.getValueAt(indiceTabela, 0);
        
        if (produtoDao.remover(codProduto)) {
            produtoListModel.removeModel(indiceTabela);
        } else {
            JOptionPane.showMessageDialog(this, "Nao foi possivel remover este produto");
        }
    }//GEN-LAST:event_btRemoverProdutoActionPerformed

    private void btEditarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarProdutoActionPerformed
        //armazena a linha selecionada da tabela
        int indiceTabela = tabelaProdutos.getSelectedRow();
        // Captura cada informação das colunas da JTable, conforme a linha selecionada
        int codigo = (Integer) produtoListModel.getValueAt(indiceTabela, 0);
        String nome = (String) produtoListModel.getValueAt(indiceTabela, 1);
        String setor = (String) produtoListModel.getValueAt(indiceTabela, 2);
        int quantidade = (Integer) produtoListModel.getValueAt(indiceTabela, 3);
        double precoCusto = (Double) produtoListModel.getValueAt(indiceTabela, 4);
        double precoVenda = (Double) produtoListModel.getValueAt(indiceTabela, 5);
        
        //Atribui os valores de produto, conforme o que foi selecionado.
        Produto produto = new Produto();
        produto.setCodigo(codigo);
        produto.setSetor(setor);
        produto.setNome(nome);
        produto.setQuantidade(quantidade);
        produto.setPrecoCusto(precoCusto);
        produto.setPrecoVenda(precoVenda);
        
        //Copia esses dados de produto para um formulário de edição
        FormularioEditarProduto formProduto = new FormularioEditarProduto(produto);
        formProduto.setDados(produto);
        getParent().add(formProduto);
        formProduto.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_btEditarProdutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btEditarProduto;
    private javax.swing.JButton btRemoverProduto;
    private javax.swing.JComboBox<String> jCEscolha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtCodigo;
    private javax.swing.JTable tabelaProdutos;
    // End of variables declaration//GEN-END:variables
}
