/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.edu.utfpr.view;

import br.edu.utfpr.DAO.FuncionarioDao;
import br.edu.utfpr.entidades.Funcionario;
import javax.swing.JOptionPane;

/**
 *
 * @author kelly
 */
public class FormularioFuncionario extends javax.swing.JInternalFrame {
    FuncionarioDao funcionarioDao = new FuncionarioDao();
    Funcionario funcionario;
    /**
     * Creates new form FormularioFuncionario
     */
    public FormularioFuncionario() {
        initComponents();
    }
    
    public FormularioFuncionario(Funcionario funcionario) {
        initComponents();
        this.funcionario = funcionario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        brCadastrarFuncionario = new javax.swing.JButton();
        btEditarFuncionario = new javax.swing.JButton();
        nomeFunc = new javax.swing.JTextField();
        funcaoFunc = new javax.swing.JTextField();
        salarioBrutoFunc = new javax.swing.JTextField();
        comissaoFunc = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Nome:");

        jLabel2.setText("Função:");

        jLabel3.setText("Salário bruto:");

        jLabel4.setText("Comissão:");

        brCadastrarFuncionario.setText("Cadastrar");
        brCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brCadastrarFuncionarioActionPerformed(evt);
            }
        });

        btEditarFuncionario.setText("Editar");
        btEditarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarFuncionarioActionPerformed(evt);
            }
        });

        nomeFunc.setColumns(20);

        funcaoFunc.setColumns(20);

        salarioBrutoFunc.setColumns(20);

        comissaoFunc.setColumns(20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(funcaoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(salarioBrutoFunc, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                    .addComponent(comissaoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(brCadastrarFuncionario)
                        .addGap(63, 63, 63)
                        .addComponent(btEditarFuncionario)))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(nomeFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(funcaoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(salarioBrutoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comissaoFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brCadastrarFuncionario)
                    .addComponent(btEditarFuncionario))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brCadastrarFuncionarioActionPerformed
        Funcionario funcionario = new Funcionario();
        funcionario.setFuncaoFuncionario(funcaoFunc.getText());
        funcionario.setNomeFuncionario(nomeFunc.getText());
        funcionario.setSalarioBrutoFuncionario(Double.parseDouble(salarioBrutoFunc.getText()));
        funcionario.setComissao(Double.parseDouble(comissaoFunc.getText()));
        funcionario.calculaSalarioLiquidoFuncionario();
        funcionarioDao.inserir(funcionario);
        JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso!");
    }//GEN-LAST:event_brCadastrarFuncionarioActionPerformed

    private void btEditarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarFuncionarioActionPerformed
        FuncionarioDao funcionarioDao = new FuncionarioDao();
        funcionario.setFuncaoFuncionario(funcaoFunc.getText());
        funcionario.setNomeFuncionario(nomeFunc.getText());
        funcionario.setSalarioBrutoFuncionario(Double.parseDouble(salarioBrutoFunc.getText()));
        funcionario.setComissao(Double.parseDouble(comissaoFunc.getText()));
        funcionario.calculaSalarioLiquidoFuncionario();
        funcionarioDao.alterar(funcionario);
        JOptionPane.showMessageDialog(this, "Funcionario editado com sucesso!");
    }//GEN-LAST:event_btEditarFuncionarioActionPerformed

    public void setDados(Funcionario funcionario){
       nomeFunc.setText(funcionario.getNomeFuncionario());
       funcaoFunc.setText(funcionario.getFuncaoFuncionario());
       salarioBrutoFunc.setText(String.valueOf(funcionario.getSalarioBrutoFuncionario()));
       comissaoFunc.setText(String.valueOf(funcionario.getComissao()));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brCadastrarFuncionario;
    private javax.swing.JButton btEditarFuncionario;
    private javax.swing.JTextField comissaoFunc;
    private javax.swing.JTextField funcaoFunc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField nomeFunc;
    private javax.swing.JTextField salarioBrutoFunc;
    // End of variables declaration//GEN-END:variables
}
